{
 "title": "Telnet",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time wasted",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_pit_total_trapped_time_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current connected clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_pit_current_connected_clients",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "telnet_pit_total_connects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (ip) (telnet_pit_clients))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent connections over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "telnet_pit_current_connected_clients",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (telnet_pit_clients)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "targets": [
    { "expr": "telnet_pit_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "telnet_pit_clients", "legendFormat": "__auto" }
   ]
  }
 ]
}